# # Application Settings
spring.application.name=TrackDonationService
server.port=8080

# # Database Configuration (PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.cloud.aws.region.static=us-east-1


# # App Queues and Topics
app.aws.sqs.allocation-commands=${SQS_ALLOCATION_COMMANDS}
app.aws.sqs.incident-events=${SQS_INCIDENT_EVENTS}
app.aws.sns.notifications-topic=${SNS_NOTIFICATIONS_TOPIC}
app.aws.sns.timeline-events=${SNS_TIMELINE_EVENTS}
app.aws.sns.admin-alerts-topic=${SNS_ADMIN_ALERTS_TOPIC}

# # External Service URLs
app.incident-service.url=${INCIDENT_SERVICE_URL}
app.resource-service.url=${RESOURCE_SERVICE_URL}

# # Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n

