# Application Settings
spring.application.name=TrackDonationService
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS Configuration
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:dummy-access-key}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:dummy-secret-key}
spring.cloud.aws.region.static=${AWS_REGION:ap-southeast-1}