# Application Settings
spring.application.name=TrackDonationService
server.port=8080

# Database Configuration (PostgreSQL)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS Configuration (Localstack/Mock for Development)
spring.cloud.aws.credentials.access-key=test-access-key
spring.cloud.aws.credentials.secret-key=test-secret-key
spring.cloud.aws.region.static=us-east-1
# spring.cloud.aws.sqs.endpoint=http://localhost:4566 # for Localstack
# spring.cloud.aws.sns.endpoint=http://localhost:4566 # for Localstack

# App Queues and Topics
app.aws.sqs.allocation-commands=donation.allocation.commands
app.aws.sns.notifications-topic=donation-notifications
